services:
  web:
    build: .
    restart: always
    expose:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://threaducation_user:threads_t0_masses@62.109.26.235:5432/education_db
      - PYTHONPATH=/app
      - OLLAMA_API_URL=http://62.109.26.235:11434
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`sber.levandrovskiy.ru`)"

  # caddy:
  #   image: caddy:2-alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - app-network
  #   depends_on:
  #     - web

  # ollama:
  #   image: docker.io/ollama/ollama:latest
  #   restart: always
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - app-network

volumes:
  ollama_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge 