services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://threaducation_user:threads_t0_masses@62.109.26.235:5432/education_db
      - PYTHONPATH=/app
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    entrypoint: ["/bin/bash", "-c"]
    command: |
      ollama serve &
      echo "Ждем запуска сервера Ollama..."
      while ! nc -z localhost 11434; do sleep 1; done
      echo "Сервер запущен, загружаем модель gemma3..."
      ollama pull gemma3
      echo "Готово. Контейнер будет оставаться активным."
      tail -f /dev/null

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge 