version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://threaducation_user:threads_t0_masses@62.109.26.235:5432/education_db
      - PYTHONPATH=/app
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull gemma3 &&
             tail -f /dev/null"

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge 